### PR TITLE
Improve sidebar

### PR DESCRIPTION
**Pull request by Itxaka**
Adds icons to each entry
Nav bar is collapsed by default as it now covers the full side on any monitor and hides part of the docs

### CODE REVIEW

**Comment by Itxaka** [comment]
image

**Comment by Itxaka** [comment]
Could also add the foldable to indicate that the sections can be expanded:

image

**Review by mauromorales — APPROVED** [review]
😎

**Comment by Itxaka** [comment]
> @Itxaka does the foldable take care that the open one has the triangle looking down? otherwise better not add

yep, its theusual triangle thing that points down when expanded, and rigth when not.

Note that that is not part of this PR as I was not sure of adding it. IMHO it looks uglier but its a good UX to show that it can be expanded...

**Comment by Itxaka** [comment]
cc @jimmykarily @mudler any thougths on this? foldable vs non foldable, nice looking vs good UX, icons opinions?

**Comment by jimmykarily** [comment]
I like the arrows. Icons look good too.

**Comment by Itxaka** [comment]
arrows it is then.

**Pull request merged**
