### PR TITLE
Write down the ordering of config read

### PR DESCRIPTION
**Pull request by Itxaka**
part of https://github.com/kairos-io/kairos-agent/pull/562

### CODE REVIEW

**Comment by Itxaka** [comment]
netlify hello?

**Review by mauromorales — APPROVED** [review]
lgtm ... maybe worth mentioning that the user can do a kairos-agent config to check the final config or so?

**Review by jimmykarily — APPROVED** [review]
Pending the removal of the `/system/oem` directory (as discussed here too: https://github.com/kairos-io/kairos-agent/pull/550#discussion_r1776700842)

**Comment by Itxaka** [comment]
agent pr is merged so order can now be merged

**Pull request merged**
